import { Injectable } from '@angular/core';
import { Person } from './person';

@Injectable()

export class PersonGenerator {

    surnames = [
        { male: 'Nowak', female: 'Nowak'},
        { male: 'Kowalski', female: 'Kowalska'},
        { male: 'Wiśniewski', female: 'Wiśniewska'},
        { male: 'Wójcik', female: 'Wójcik'},
        { male: 'Kowalczyk', female: 'Kowalczyk'},
        { male: 'Kamiński', female: 'Kamińska'},
        { male: 'Lewandowski', female: 'Lewandowska'},
        { male: 'Zieliński', female: 'Zielińska'},
        { male: 'Szymański', female: 'Szymańska'},
        { male: 'Woźniak', female: 'Woźniak'},
        { male: 'Dąbrowski', female: 'Dąbrowska'},
        { male: 'Kozłowski', female: 'Kozłowska'},
        { male: 'Jankowski', female: 'Jankowska'},
        { male: 'Mazur', female: 'Mazur'},
        { male: 'Wojciechowski', female: 'Wojciechowska'},
        { male: 'Kwiatkowski', female: 'Kwiatkowska'},
        { male: 'Krawczyk', female: 'Krawczyk'},
        { male: 'Kaczmarek', female: 'Kaczmarek'},
        { male: 'Piotrowski', female: 'Piotrowska'},
        { male: 'Grabowski', female: 'Grabowska'},
        { male: 'Zając', female: 'Zając'},
        { male: 'Pawłowski', female: 'Pawłowska'},
        { male: 'Michalski', female: 'Michalska'},
        { male: 'Król', female: 'Król'},
        { male: 'Wieczorek', female: 'Wieczorek'},
        { male: 'Jabłoński', female: 'Jabłońska'},
        { male: 'Wróbel', female: 'Wróbel'},
        { male: 'Nowakowski', female: 'Nowakowska'},
        { male: 'Majewski', female: 'Majewska'},
        { male: 'Olszewski', female: 'Olszewska'},
        { male: 'Stępień', female: 'Stępień'},
        { male: 'Malinowski', female: 'Malinowska'},
        { male: 'Jaworski', female: 'Jaworska'},
        { male: 'Adamczyk', female: 'Adamczyk'},
        { male: 'Dudek', female: 'Dudek'},
        { male: 'Nowicki', female: 'Nowicka'},
        { male: 'Pawlak', female: 'Pawlak'},
        { male: 'Górski', female: 'Górska'},
        { male: 'Witkowski', female: 'Witkowska'},
        { male: 'Walczak', female: 'Walczak'},
        { male: 'Sikora', female: 'Sikora'},
        { male: 'Baran', female: 'Baran'},
        { male: 'Rutkowski', female: 'Rutkowska'},
        { male: 'Michalak', female: 'Michalak'},
        { male: 'Szewczyk', female: 'Szewczyk'},
        { male: 'Ostrowski', female: 'Ostrowska'},
        { male: 'Tomaszewski', female: 'Tomaszewska'},
        { male: 'Pietrzak', female: 'Pietrzak'},
        { male: 'Zalewski', female: 'Zalewska'},
        { male: 'Wróblewski', female: 'Wróblewska'},
        { male: 'Marciniak', female: 'Marciniak'},
        { male: 'Jasiński', female: 'Jasińska'},
        { male: 'Zawadzki', female: 'Zawadzka'},
        { male: 'Bąk', female: 'Bąk'},
        { male: 'Jakubowski', female: 'Jakubowska'},
        { male: 'Sadowski', female: 'Sadowska'},
        { male: 'Duda', female: 'Duda'},
        { male: 'Włodarczyk', female: 'Włodarczyk'},
        { male: 'Wilk', female: 'Wilk'},
        { male: 'Chmielewski', female: 'Chmielewska'},
        { male: 'Borkowski', female: 'Borkowska'},
        { male: 'Sokołowski', female: 'Sokołowska'},
        { male: 'Szczepański', female: 'Szczepańska'},
        { male: 'Sawicki', female: 'Sawicka'},
        { male: 'Kucharski', female: 'Kucharska'},
        { male: 'Lis', female: 'Lis'},
        { male: 'Maciejewski', female: 'Maciejewska'},
        { male: 'Kubiak', female: 'Kubiak'},
        { male: 'Kalinowski', female: 'Kalinowska'},
        { male: 'Mazurek', female: 'Mazurek'},
        { male: 'Wysocki', female: 'Wysocka'},
        { male: 'Kołodziej', female: 'Kołodziej'},
        { male: 'Kaźmierczak', female: 'Kaźmierczak'},
        { male: 'Czarnecki', female: 'Czarnecka'},
        { male: 'Sobczak', female: 'Sobczak'},
        { male: 'Konieczny', female: 'Konieczna'},
        { male: 'Urbański', female: 'Urbańska'},
        { male: 'Głowacki', female: 'Głowacka'},
        { male: 'Wasilewski', female: 'Wasilewska'},
        { male: 'Sikorski', female: 'Sikorska'},
        { male: 'Zakrzewski', female: 'Zakrzewska'},
        { male: 'Krajewski', female: 'Krajewska'},
        { male: 'Krupa', female: 'Krupa'},
        { male: 'Laskowski', female: 'Laskowska'},
        { male: 'Ziółkowski', female: 'Ziółkowska'},
        { male: 'Gajewski', female: 'Gajewska'},
        { male: 'Mróz', female: 'Mróz'},
        { male: 'Brzeziński', female: 'Brzezińska'},
        { male: 'Szulc', female: 'Szulc'},
        { male: 'Szymczak', female: 'Szymczak'},
        { male: 'Makowski', female: 'Makowska'},
        { male: 'Baranowski', female: 'Baranowska'},
        { male: 'Przybylski', female: 'Przybylska'},
        { male: 'Kaczmarczyk', female: 'Kaczmarczyk'},
        { male: 'Borowski', female: 'Borowska'},
        { male: 'Błaszyk', female: 'Błaszyk'},
        { male: 'Adamski', female: 'Adamska'},
        { male: 'Górecki', female: 'Górecka'},
        { male: 'Chojnacki', female: 'Chojnacka'},
        { male: 'Kania', female: 'Kania'},
        { male: 'Leszczyński', female: 'Leszczyńska'},
        { male: 'Janik', female: 'Janik'},
        { male: 'Szczepaniak', female: 'Szczepaniak'},
        { male: 'Czerwiński', female: 'Czerwińska'},
        { male: 'Kozioł', female: 'Kozioł'},
        { male: 'Mucha', female: 'Mucha'},
        { male: 'Lipiński', female: 'Lipińska'},
        { male: 'Wesołowski', female: 'Wesołowska'},
        { male: 'Kozak', female: 'Kozak'},
        { male: 'Cieślak', female: 'Cieślak'},
        { male: 'Kowalewski', female: 'Kowalewska'},
        { male: 'Andrzejewski', female: 'Andrzejewska'},
        { male: 'Mikołajczyk', female: 'Mikołajczyk'},
        { male: 'Jarosz', female: 'Jarosz'},
        { male: 'Musiał', female: 'Musiał'},
        { male: 'Zięba', female: 'Zięba'},
        { male: 'Kowalik', female: 'Kowalik'},
        { male: 'Kołodziejczyk', female: 'Kołodziejczyk'},
        { male: 'Markowski', female: 'Markowska'},
        { male: 'Brzozowski', female: 'Brzozowska'},
        { male: 'Kopeć ', female: 'Kopeć '},
        { male: 'Nowacki ', female: 'Nowacka '},
        { male: 'Orłowski ', female: 'Orłowska '},
        { male: 'Domański ', female: 'Domańska '},
        { male: 'Żak ', female: 'Żak '},
        { male: 'Tomczyk ', female: 'Tomczyk '},
        { male: 'Kurek ', female: 'Kurek '},
        { male: 'Piątek ', female: 'Piątek '},
        { male: 'Pawlik ', female: 'Pawlik '},
        { male: 'Tomczak ', female: 'Tomczak '},
        { male: 'Markiewicz ', female: 'Markiewicz '},
        { male: 'Ciesielski ', female: 'Ciesielska '},
        { male: 'Wawrzyniak ', female: 'Wawrzyniak '},
        { male: 'Kot ', female: 'Kot '},
        { male: 'Wójtowicz ', female: 'Wójtowicz '},
        { male: 'Polak ', female: 'Polak '},
        { male: 'Wolski ', female: 'Wolska '},
        { male: 'Kruk ', female: 'Kruk '},
        { male: 'Stasiak ', female: 'Stasiak '},
        { male: 'Stankiewicz', female: 'Stankiewicz'},
        { male: 'Sowa ', female: 'Sowa '},
        { male: 'Łuczak ', female: 'Łuczak '},
        { male: 'Wierzbicki ', female: 'Wierzbicka '},
        { male: 'Jastrzębski ', female: 'Jastrzębska '},
        { male: 'Urbaniak ', female: 'Urbaniak '},
        { male: 'Karpiński ', female: 'Karpińska '},
        { male: 'Czajkowski ', female: 'Czajkowska '},
        { male: 'Piasecki ', female: 'Piasecka '},
        { male: 'Gajda ', female: 'Gajda '},
        { male: 'Nawrocki ', female: 'Nawrocka '},
        { male: 'Bednarek ', female: 'Bednarek '},
        { male: 'Stefański ', female: 'Stefańska '},
        { male: 'Klimek ', female: 'Klimek '},
        { male: 'Janicki ', female: 'Janicka '},
        { male: 'Jóźwiak ', female: 'Jóźwiak '},
        { male: 'Dziedzic ', female: 'Dziedzic '},
        { male: 'Sosnowski ', female: 'Sosnowska '},
        { male: 'Bielecki ', female: 'Bielecka '},
        { male: 'Majchrzak ', female: 'Majchrzak '},
        { male: 'Madej', female: 'Madej'},
        { male: 'Leśniak ', female: 'Leśniak '},
        { male: 'Milewski ', female: 'Milewska '},
        { male: 'Maj ', female: 'Maj '},
        { male: 'Kowal ', female: 'Kowal '},
        { male: 'Małecki ', female: 'Małecka '},
        { male: 'Śliwiński ', female: 'Śliwińska '},
        { male: 'Socha ', female: 'Socha '},
        { male: 'Skiba ', female: 'Skiba '},
        { male: 'Marek ', female: 'Marek '},
        { male: 'Dobrowolski ', female: 'Dobrowoska '},
        { male: 'Domagała ', female: 'Domagała '},
        { male: 'Bednarczyk ', female: 'Bednarczyk '},
        { male: 'Wrona ', female: 'Wrona '},
        { male: 'Urban ', female: 'Urban '},
        { male: 'Olejniczak ', female: 'Olejniczak '},
        { male: 'Pająk ', female: 'Pająk '},
        { male: 'Matuszewski ', female: 'Matuszewska '},
        { male: 'Romanowski ', female: 'Romanowska '},
        { male: 'Kasprzak ', female: 'Kasprzak '},
        { male: 'Świątek', female: 'Świątek'},
        { male: 'Wilczyński ', female: 'Wilczyńska '},
        { male: 'Ratajczak ', female: 'Ratajczak '},
        { male: 'Kurowski ', female: 'Kurowska '},
        { male: 'Michalik ', female: 'Michalik '},
        { male: 'Owczarek ', female: 'Owczarek '},
        { male: 'Orzechowski ', female: 'Orzechowska '},
        { male: 'Grzelak ', female: 'Grzelak '},
        { male: 'Łukasik ', female: 'Łukasik '},
        { male: 'Olejnik ', female: 'Olejnik '},
        { male: 'Sobolewski ', female: 'Sobolewska '},
        { male: 'Rogowski ', female: 'Rogowska '},
        { male: 'Mazurkiewicz ', female: 'Mazurkiewicz '},
        { male: 'Barański ', female: 'Barańska '},
        { male: 'Bukowski ', female: 'Bukowska '},
        { male: 'Matusiak ', female: 'Matusiak '},
        { male: 'Sroka ', female: 'Sroka '},
        { male: 'Kosiński ', female: 'Kosińska '},
        { male: 'Kędzierski ', female: 'Kędzierska '},
        { male: 'Skowroński ', female: 'Skowrońska '},
        { male: 'Marcinkowski', female: 'Marcinkowska'},
        { male: 'Sobczyk ', female: 'Sobczyk '},
        { male: 'Kozieł ', female: 'Kozieł '},
        { male: 'Marszałek ', female: 'Marszałek '},
        { male: 'Zych ', female: 'Zych '},
        { male: 'Chrzanowski ', female: 'Chrzanowska '},
        { male: 'Bednarski ', female: 'Bednarska '},
        { male: 'Rybak ', female: 'Rybak '},
        { male: 'Lisowski ', female: 'Lisowska '},
        { male: 'Bednarz ', female: 'Bednarz '},
        { male: 'Janiszewski ', female: 'Janiszewska '},
        { male: 'Pluta ', female: 'Pluta '},
        { male: 'Kasprzyk ', female: 'Kasprzyk '},
        { male: 'Muszyński ', female: 'Muszyńska '},
        { male: 'Kwiecień ', female: 'Kwiecień '},
        { male: 'Kuczyński ', female: 'Kuczyńska '},
        { male: 'Świderski ', female: 'Świderska '},
        { male: 'Paluch ', female: 'Paluch '},
        { male: 'Morawski ', female: 'Morawska '},
        { male: 'Białek ', female: 'Białek '},
        { male: 'Grzybowski', female: 'Grzybowska'},
        { male: 'Witek ', female: 'Witek '},
        { male: 'Turek ', female: 'Turek '},
        { male: 'Marczak ', female: 'Marczak '},
        { male: 'Jędrzejewski ', female: 'Jędrzejewska '},
        { male: 'Osiński ', female: 'Osińska '},
        { male: 'Marzec ', female: 'Marzec '},
        { male: 'Chmiel ', female: 'Chmiel '},
        { male: 'Czajka ', female: 'Czajka '},
        { male: 'Kaczor ', female: 'Kaczor '},
        { male: 'Małek ', female: 'Małek '},
        { male: 'Kubicki ', female: 'Kubicka '},
        { male: 'Krzemiński ', female: 'Krzemińska '},
        { male: 'Łukowski ', female: 'Łukowska '},
        { male: 'Piekarski ', female: 'Piekarska '},
        { male: 'Michałowski ', female: 'Michałowska '},
        { male: 'Szczęsny ', female: 'Szczęsny '},
        { male: 'Szydłowski ', female: 'Szydłowska '},
        { male: 'Biernacki ', female: 'Biernacka '},
        { male: 'Śliwa ', female: 'Śliwa '},
        { male: 'Janowski', female: 'Janowska'},
        { male: 'Stefaniak', female: 'Stefaniak'},
        { male: 'Lechicki', female: 'Lechicka'},
        { male: 'Przybysz', female: 'Przybysz'},
        { male: 'Lewicki', female: 'Lewicka'},
        { male: 'Gołębiewski', female: 'Gołębiewska'},
        { male: 'Murawski', female: 'Murawska'},
        { male: 'Dębski', female: 'Dębska'},
        { male: 'Kulesza', female: 'Kulesza'},
        { male: 'Popławski', female: 'Popławska'},
        { male: 'Staniszewski', female: 'Staniszewska'}
    ];

    names = [
        { male: 'Jakub', female: 'Zuzanna'},
        { male: 'Antoni', female: 'Lena'},
        { male: 'Szymon', female: 'Julia'},
        { male: 'Jan', female: 'Maja'},
        { male: 'Filip', female: 'Zofia'},
        { male: 'Kacper', female: 'Hanna'},
        { male: 'Aleksander', female: 'Amelia'},
        { male: 'Franciszek', female: 'Aleksandra'},
        { male: 'Mikołaj', female: 'Alicja'},
        { male: 'Wojciech', female: 'Natalia'},
        { male: 'Adam', female: 'Wiktoria'},
        { male: 'Michał', female: 'Oliwia'},
        { male: 'Marcel', female: 'Maria'},
        { male: 'Wiktor', female: 'Emilia'},
        { male: 'Piotr', female: 'Nikola'},
        { male: 'Igor', female: 'Liliana'},
        { male: 'Mateusz', female: 'Anna'},
        { male: 'Bartosz', female: 'Antonina'},
        { male: 'Stanisław', female: 'Nadia'},
        { male: 'Alan', female: 'Gabriela'},
        { male: 'Nikodem', female: 'Laura'},
        { male: 'Dawid', female: 'Milena'},
        { male: 'Miłosz', female: 'Iga'},
        { male: 'Maksymilian', female: 'Martyna'},
        { male: 'Leon', female: 'Pola'},
        { male: 'Oliwier', female: 'Kornelia'},
        { male: 'Karol', female: 'Magdalena'},
        { male: 'Oskar', female: 'Karolina'},
        { male: 'Maciej', female: 'Michalina'},
        { male: 'Tomasz', female: 'Weronika'},
        { male: 'Natan', female: 'Marcelina'},
        { male: 'Dominik', female: 'Agata'},
        { male: 'Krzysztof', female: 'Jagoda'},
        { male: 'Tymon', female: 'Helena'},
        { male: 'Fabian', female: 'Nina'},
        { male: 'Hubert', female: 'Barbara'},
        { male: 'Paweł', female: 'Blanka'},
        { male: 'Ignacy', female: 'Kinga'},
        { male: 'Tymoteusz', female: 'Paulina'},
        { male: 'Julian', female: 'Łucja'},
        { male: 'Kamil', female: 'Joanna'},
        { male: 'Patryk', female: 'Kaja'},
        { male: 'Gabriel', female: 'Małgorzata'},
        { male: 'Bartłomiej', female: 'Marta'},
        { male: 'Ksawery', female: 'Patrycja'},
        { male: 'Sebastian', female: 'Katarzyna'},
        { male: 'Adrian', female: 'Anastazja'},
        { male: 'Krystian', female: 'Dominika'},
        { male: 'Kajetan', female: 'Klaudia'},
        { male: 'Olaf', female: 'Lilianna'},
        { male: 'Łukasz', female: 'Aniela'},
        { male: 'Błażej', female: 'Klara'},
        { male: 'Marcin', female: 'Nela'},
        { male: 'Borys', female: 'Sara'},
        { male: 'Eryk', female: 'Izabela'},
        { male: 'Kuba', female: 'Ewa'},
        { male: 'Artur', female: 'Eliza'},
        { male: 'Daniel', female: 'Kamila'},
        { male: 'Bruno', female: 'Matylda'},
        { male: 'Grzegorz', female: 'Olga'},
        { male: 'Damian', female: 'Kalina'},
        { male: 'Przemysław', female: 'Urszula'},
        { male: 'Rafał', female: 'Daria'},
        { male: 'Tobiasz', female: 'Adrianna'},
        { male: 'Cezary', female: 'Malwina'},
        { male: 'Olivier', female: 'Dorota'},
        { male: 'Konrad', female: 'Lidia'},
        { male: 'Emil', female: 'Sandra'},
        { male: 'Radosław', female: 'Bianka'},
        { male: 'Nataniel', female: 'Liwia'},
        { male: 'Alex', female: 'Roksana'},
        { male: 'Marek', female: 'Rozalia'},
        { male: 'Robert', female: 'Karina'},
        { male: 'Witold', female: 'Marianna'},
        { male: 'Gracjan', female: 'Marika'},
        { male: 'Tadeusz', female: 'Justyna'},
        { male: 'Kornel', female: 'Mia'},
        { male: 'Milan', female: 'Natasza'},
        { male: 'Jerzy', female: 'Aurelia'},
        { male: 'Aleks', female: 'Ada'},
        { male: 'Mieszko', female: 'Nicola'},
        { male: 'Andrzej', female: 'Vanessa'},
        { male: 'Arkadiusz', female: 'Monika'},
        { male: 'Iwo', female: 'Agnieszka'},
        { male: 'Stefan', female: 'Inga'},
        { male: 'Alexander', female: 'Olivia'},
        { male: 'Dorian', female: 'Emma'},
        { male: 'Ryszard', female: 'Jowita'},
        { male: 'Brajan', female: 'Marlena'},
        { male: 'Jacek', female: 'Melania'},
        { male: 'Leonard', female: 'Elena'},
        { male: 'Gustaw', female: 'Dagmara'},
        { male: 'Kazimierz', female: 'Diana'},
        { male: 'Konstanty', female: 'Victoria'},
        { male: 'Juliusz', female: 'Julita'},
        { male: 'Józef', female: 'Nel'},
        { male: 'Norbert', female: 'Apolonia'},
        { male: 'Jeremi', female: 'Luiza'},
        { male: 'Seweryn', female: 'Sonia'},
        { male: 'Feliks', female: 'Lilia'},
        { male: 'Henryk', female: 'Ewelina'},
        { male: 'Teodor', female: 'Rita'},
        { male: 'Oliver', female: 'Ida'},
        { male: 'Jędrzej', female: 'Anita'},
        { male: 'Albert', female: 'Zoja'},
        { male: 'Samuel', female: 'Jessica'},
        { male: 'Cyprian', female: 'Julianna'},
        { male: 'Remigiusz', female: 'Elżbieta'},
        { male: 'Dariusz', female: 'Jadwiga'},
        { male: 'Ernest', female: 'Tola'},
        { male: 'Florian', female: 'Gaja'},
        { male: 'Leo', female: 'Krystyna'},
        { male: 'Ludwik', female: 'Wanda'},
        { male: 'Aleksy', female: 'Janina'},
        { male: 'Mariusz', female: 'Sabina'},
        { male: 'Maksym', female: 'Alina'},
        { male: 'Maurycy', female: 'Adela'},
        { male: 'Kordian', female: 'Paula'},
        { male: 'Lucjan', female: 'Amanda'},
        { male: 'David', female: 'Izabella'},
        { male: 'Fryderyk', female: 'Celina'},
        { male: 'Maximilian', female: 'Antonia'},
        { male: 'Tytus', female: 'Sylwia'},
        { male: 'Hugo', female: 'Angelika'},
        { male: 'Beniamin', female: 'Nicole'},
        { male: 'Władysław', female: 'Stefania'},
        { male: 'Xavier', female: 'Lea'},
        { male: 'Kevin', female: 'Lila'},
        { male: 'Nathan', female: 'Judyta'},
        { male: 'Szczepan', female: 'Faustyna'},
        { male: 'Jeremiasz', female: 'Magda'},
        { male: 'Ksawier', female: 'Teresa'},
        { male: 'Nicolas', female: 'Otylia'},
        { male: 'Max', female: 'Jagna'},
        { male: 'Sylwester', female: 'Estera'},
        { male: 'Joachim', female: 'Konstancja'},
        { male: 'Sławomir', female: 'Mila'},
        { male: 'Sergiusz', female: 'Jaśmina'},
        { male: 'Olgierd', female: 'Ines'},
        { male: 'Oliwer', female: 'Aneta'},
        { male: 'Zbigniew', female: 'Noemi'},
        { male: 'Amadeusz', female: 'Tatiana'},
        { male: 'Vincent', female: 'Inez'},
        { male: 'Jonasz', female: 'Viktoria'},
        { male: 'Aron', female: 'Tamara'},
        { male: 'Brayan', female: 'Hana'},
        { male: 'Maks', female: 'Livia'},
        { male: 'Marceli', female: 'Edyta'},
        { male: 'Edward', female: 'Malina'},
        { male: 'Oktawian', female: 'Beata'},
        { male: 'Ivo', female: 'Samanta'},
        { male: 'Kosma', female: 'Marcela'},
        { male: 'Oleg', female: 'Danuta'},
        { male: 'Jarosław', female: 'Sofia'},
        { male: 'Miron', female: 'Irena'},
        { male: 'Nikolas', female: 'Klementyna'},
        { male: 'Janusz', female: 'Olimpia'},
        { male: 'Benjamin', female: 'Lucyna'},
        { male: 'Jonatan', female: 'Oktawia'},
        { male: 'Roman', female: 'Felicja'},
        { male: 'Kasjan', female: 'Berenika'},
        { male: 'Leonardo', female: 'Gloria'},
        { male: 'Victor', female: 'Ola'},
        { male: 'Bernard', female: 'Franciszka'},
        { male: 'Michael', female: 'Halina'},
        { male: 'Emilian', female: 'Lara'},
        { male: 'Korneliusz', female: 'Larysa'},
        { male: 'Kaspian', female: 'Marzena'},
        { male: 'Bolesław', female: 'Andżelika'},
        { male: 'Gniewko', female: 'Jolanta'},
        { male: 'Oscar', female: 'Adriana'},
        { male: 'Leszek', female: 'Jana'},
        { male: 'Maxymilian', female: 'Stella'},
        { male: 'Bronisław', female: 'Ilona'},
        { male: 'Martin', female: 'Melisa'},
        { male: 'Zygmunt', female: 'Emilia'},
        { male: 'Aaron', female: 'Inka'},
        { male: 'Kewin', female: 'Lilla'},
        { male: 'Wincenty', female: 'Alicja'},
        { male: 'Denis', female: 'Cecylia'},
        { male: 'Brian', female: 'Mira'},
        { male: 'Nathaniel', female: 'Oksana'},
        { male: 'Roch', female: 'Honorata'},
        { male: 'Ziemowit', female: 'Ksenia'},
        { male: 'Bryan', female: 'Żaneta'},
        { male: 'Cyryl', female: 'Florentyna'},
        { male: 'Gniewomir', female: 'Lilia'},
        { male: 'Leopold', female: 'Roma'},
        { male: 'Viktor', female: 'Wioletta'},
        { male: 'Allan', female: 'Aleksandra'},
        { male: 'Ariel', female: 'Greta'},
        { male: 'Bogumił', female: 'Idalia'},
        { male: 'Klemens', female: 'Ina'},
        { male: 'Marian', female: 'Iwona'},
        { male: 'Ryan', female: 'Marcjanna'},
        { male: 'Xawery', female: 'Nikola'},
        { male: 'Eliasz', female: 'Sara'},
        { male: 'Jonathan', female: 'Zofia'},
        { male: 'Wincent', female: 'Aurora'},
        { male: 'Alek', female: 'Carmen'}
    ];

    departments = [
        'PZ', 'PZ / DF', 'PZ / DT', 'PZ / DR', 'PZ / DW',
        'PZ / DF / FK', 'PZ / DF / EA', 'PZ / DF / RP',
        'PZ / DT / WT', 'PZ / DT / WM', 'PZ / DT / EL', 'PZ / DT / BK',
        'PZ / DR / HR', 'PZ / DR / DS', 'PZ / DR / BH',
        'PZ / DW / DO', 'PZ / DW / RP', 'PZ / DW / KG', 'PZ / DW / ZL', 'PZ / DW / JG'
    ];

    positions = [
        'Specjalista', 'Młodszy Specjalista', 'Starszy Specjalista', 'Analityk', 'Koordynator', 'Asystent',
        'Kierownik Zespołu', 'Referent', 'Młodszy Referent'
    ];

    getRandom(start: number, end: number): number {
        return Math.floor((Math.random() * (end - start + 1)) + start);
    }


    private makeEmail(email: string): string {
        return email
            .replace(/ą/ig,  'a').replace(/Ą/ig, 'A')
            .replace(/ć/ig,  'c').replace(/Ć/ig, 'C')
            .replace(/ę/ig,  'e').replace(/Ę/ig, 'E')
            .replace(/ł/ig,  'l').replace(/Ł/ig, 'L')
            .replace(/ń/ig,  'n').replace(/Ń/ig, 'N')
            .replace(/ó/ig,  'o').replace(/Ó/ig, 'O')
            .replace(/ś/ig,  's').replace(/Ś/ig, 'S')
            .replace(/ż/ig,  'z').replace(/Ż/ig, 'Z')
            .replace(/ź/ig,  'z').replace(/Ź/ig, 'Z');
    }

    generatePerson(): Person {

        const newPerson = new Person();
        const gender = this.getRandom( 1, 2 );

        if (gender === 1) {
            newPerson.name = this.names[this.getRandom(0, this.names.length - 1)].male.trim();
            newPerson.surname =  this.surnames[this.getRandom(0, this.surnames.length - 1)].male.trim();
        } else {
            newPerson.name = this.names[this.getRandom(0, this.names.length - 1)].female.trim();
            newPerson.surname =  this.surnames[this.getRandom(0, this.surnames.length - 1)].female.trim();
        }

        newPerson.department = this.departments[this.getRandom(0, this.departments.length - 1) ].trim();
        newPerson.position = this.positions[this.getRandom(0, this.positions.length - 1) ].trim();

        newPerson.internal = '' + this.getRandom(1000, 9999);
        newPerson.phone = '+48 (022) ' + this.getRandom(510, 597) + '-' + this.getRandom(10, 99) + '-' + this.getRandom(10, 99);
        newPerson.cellular = '' + this.getRandom(750, 882) + ' ' + this.getRandom(100, 999) + ' ' + this.getRandom(100, 999);
        newPerson.email = (newPerson.name.toLowerCase() + '.' + newPerson.surname.toLowerCase() + '@' + 'some-corporation.com');

        newPerson.email = this.makeEmail(newPerson.email);

        return newPerson;
    }
}
